[package]
name = "uutils-args-complete"
version = "0.1.0"
edition = "2021"
authors = ["Terts Diepraam"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roff = "0.2.1"